### ISSUE TITLE
investigate why racon.newAsset returns an asset variable for which there's no autocomplete in the IDE

### ISSUE THREAD

**Issue by kartben** [SierraWireless/eclipsecon2013-m2m-tutorial#6]

**Comment by lbarthelemy** [comment]
Not sure how this different from https://github.com/SierraWireless/eclipsecon2013-m2m-tutorial/issues/5

Using require"airvantage", I can use the  autocomplete correctly.

using require"racon" doesn't work: the luadoc refers explicitly to @module airvantage, the asset object is explictely named @{airvantage.asset} so I think is explains why require"racon" doesn't get autocomplete.

To do so, I think we would need to re-do the luadoc for the module...
